app/__init__.py
from app.config import ProdConfig, DevConfig
from flask import Flask


def create_app(config_classname):

    app = Flask(__name__, template_folder='../templates')
    # app.config.form_object(config_class)
    app.config.from_object(config_classname)
    from app.routes import bp_main
    app.register_blueprint(bp_main)

    return app

app/routes.py
from flask import render_template, Blueprint

bp_main = Blueprint('main', __name__)


@bp_main.route('/')
@bp_main.route('/acceuil')
def home():
    return render_template('about.html')


@bp_main.route('/annales_brevet')
def brevet_years():
    return render_template('brevet_years.html')


@bp_main.route('/version_complete')
def version_complete():
    return render_template('version_complete.html')


@bp_main.route('/annales_brevet/<id>')
def year(id):
    page = id + '.html'
    return render_template(page)


@bp_main.route('/<file_name>')
def region(file_name):
    return render_template('pdf_view.html', file_name=file_name)

templates/2018.html
{% extends 'layout.html'%}

{% block content %}
    <h1 class="margin-space align-text">Annales Brevet 2018</h1>
    <hr>
<br>
<div class="years">
    <div class="years-in">
    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (Métropole) 2018.pdf') }}">Métropole 2018 Juin (SVT + Technologie)   </a>
        <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (Métropole) 2018 Septembre.pdf') }}"> Métropole 2018 Septembre (SVT + Technologie)  </a>
   <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + Techno (Centres Étrangers) 2018.pdf') }}">   Centres Étrangers 2018 Juin (PC + Technologie)  </a>
 <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Amérique du Nord) 2018.pdf') }}">Amérique du Nord 2018 Juin (PC +SVT)   </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC (Sujet Zéro) 2018.pdf') }}">Sujet Zéro 2018 (PC)   </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT (Sujet Zéro) 2018.pdf') }}"> Sujet Zéro 2018 (SVT)  </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - Techno (Sujet Zéro) 2018.pdf') }}"> Sujet Zéro 2018 (Technologie)  </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (Pondichéry) 2018.pdf') }}"> Pondichéry 2018 Juin (SVT + Technologie)  </a>
   <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Polynésie Française) 2018.pdf') }}"> Polynésie 2018 Juin (PC + SVT)   </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Polynésie Française) 2018 Septemhre.pdf') }}">  Polynésie 2018 Septembre (PC + SVT)   </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET secours - SVT (Polynésie Française) 2018.pdf') }}"> Polynésie Secours 2018 (SVT)  </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Amérique du Sud) 2018.pdf') }}">  Amérique du Sud 2018 Novembre (PC + SVT)  </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET secours - SVT (Amérique du Sud) 2018.pdf') }}">  Amérique du Sud Secours 2018 Novembre (SVT)  </a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Asie Pacifique) 2018.pdf') }}"> Asie Pacifique 2018 (PC + SVT)  </a>
</div>
    </div>
{% endblock content %}

templates/2019.html
{% extends 'layout.html'%}

{% block content %}

<h1 class="margin-space align-text">Annales Brevet 2019</h1>
<hr><br>

    <div class="years">
    <div class="years-in">
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Métropole) 2019.pdf') }}"> Métropole 2019 Juillet (PC + SVT)</a>
<hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Métropole) 2019 Septembre.pdf') }}">Métropole 2019 Septembre (PC + SVT)</a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Métropole) 2019 Septembre.pdf') }}">Centres Étrangers 2019 Juin (PC + SVT)</a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Amérique du Nord) 2019.pdf') }}">Amérique du Nord 2019 Juin (PC + SVT)</a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (polynésie Française) 2019.pdf') }}">Polynésie 2019 Juillet (SVT + Technologie)</a>
    <hr>
     <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (polynésie Française) 2019 Septembre.pdf') }}"> Polynésie 2019 Septembre (SVT + Technologie)</a>
   <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Pondichéry) 2019.pdf') }}"> Pondichéry 2019 Juin (PC + SVT)</a>
    <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - Techno (Nouvelle Calédonie) 2019.pdf') }}"> Nouvelle Calédonie 2019 Décembre (Technologie)</a>
   <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Antilles-Guyane) 2019.pdf') }}">  Antilles-Guyane 2019 Juin (PC + SVT)</a>
   <hr>
    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Asie Pacifique) 2019.pdf') }}">  Asie Pacifique 2019 Juin (PC + SVT)</a>
    </div>
    </div>

{% endblock content %}

templates/about.html
{% extends 'layout.html' %}

{% block content %}

    <h1 class="margin-space align-text">Bonjour les 3èmes!</h1>
    <hr>
    <p class="margin-space">
        Je suis élève de Terminale du Lycée Français de Barcelone qui, comme vous, avait eu du mal à trouver
        tous les sujets des examens du brevet de sciences dans un seul endroit. J'ai donc décidé de construire ce site
        pour vous aider!<br>
        Si vous voulez proposer une correction, ne doutez pas à me le faire savoir!
        </p>

<div>
    <a class="margin-space" href = "mailto: annales.sciences.brevet@gmail.com">annales.sciences.brevet@gmail.com</a>

    <div class="margin-space">
        <a href="{{ url_for('main.brevet_years') }}"<button type="button" class="btn btn-primary btn-lg btn-block" ><h3>Annales Brevet Sciences</h3></button></a>
        <a href="{{ url_for('main.version_complete') }}"<button type="button" class="btn btn-secondary btn-lg btn-block"><h3>Version Complète</h3></button></a>
</div>


{% endblock content %}

templates/brevet_years.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="margin-space align-text">Annales Brevet</h1>
    <hr>


    <div class="margin-space">

        <button type="button" class="btn btn-primary btn-lg btn-block" data-toggle="collapse"
                data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            <h3>Brevet 2019 (10 sujets)</h3>
        </button>

        <div class="collapse" id="collapseExample">
            <div class="card card-body">

                <h1 class="margin-space align-text">Annales Brevet 2019</h1>
                <hr>
                <br>

                <div class="years">
                    <div class="years-in">
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Métropole) 2019.pdf') }}"> Métropole
                            2019 Juillet (PC + SVT)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Métropole) 2019 Septembre.pdf') }}">Métropole
                            2019 Septembre (PC + SVT)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Métropole) 2019 Septembre.pdf') }}">Centres
                            Étrangers 2019 Juin (PC + SVT)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Amérique du Nord) 2019.pdf') }}">Amérique
                            du Nord 2019 Juin (PC + SVT)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (polynésie Française) 2019.pdf') }}">Polynésie
                            2019 Juillet (SVT + Technologie)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (polynésie Française) 2019 Septembre.pdf') }}">
                            Polynésie 2019 Septembre (SVT + Technologie)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Pondichéry) 2019.pdf') }}">
                            Pondichéry 2019 Juin (PC + SVT)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - Techno (Nouvelle Calédonie) 2019.pdf') }}">
                            Nouvelle Calédonie 2019 Décembre (Technologie)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Antilles-Guyane) 2019.pdf') }}">
                            Antilles-Guyane 2019 Juin (PC + SVT)</a>
                        <hr>
                        <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Asie Pacifique) 2019.pdf') }}"> Asie
                            Pacifique 2019 Juin (PC + SVT)</a>
                    </div>
                </div>
            </div>
        </div>
<br>
    <button type="button" class="btn btn-secondary btn-lg btn-block" data-toggle="collapse"
            data-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample">
        <h3>Brevet 2018 (15 sujets)</h3>
    </button>
    <div class="collapse" id="collapseExample2">
        <div class="card card-body">
            <h1 class="margin-space align-text">Annales Brevet 2018</h1>
            <hr>
            <br>
            <div class="years">
                <div class="years-in">
                    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (Métropole) 2018.pdf') }}">Métropole
                        2018 Juin (SVT + Technologie) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (Métropole) 2018 Septembre.pdf') }}">
                        Métropole 2018 Septembre (SVT + Technologie) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + Techno (Centres Étrangers) 2018.pdf') }}">
                        Centres Étrangers 2018 Juin (PC + Technologie) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Amérique du Nord) 2018.pdf') }}">Amérique
                        du Nord 2018 Juin (PC +SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC (Sujet Zéro) 2018.pdf') }}">Sujet Zéro 2018
                        (PC) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT (Sujet Zéro) 2018.pdf') }}"> Sujet Zéro 2018
                        (SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - Techno (Sujet Zéro) 2018.pdf') }}"> Sujet Zéro
                        2018 (Technologie) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - SVT + Techno (Pondichéry) 2018.pdf') }}">
                        Pondichéry 2018 Juin (SVT + Technologie) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Polynésie Française) 2018.pdf') }}">
                        Polynésie 2018 Juin (PC + SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Polynésie Française) 2018 Septemhre.pdf') }}">
                        Polynésie 2018 Septembre (PC + SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET secours - SVT (Polynésie Française) 2018.pdf') }}">
                        Polynésie Secours 2018 (SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC + SVT (Amérique du Sud) 2018.pdf') }}">
                        Amérique du Sud 2018 Novembre (PC + SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET secours - SVT (Amérique du Sud) 2018.pdf') }}">
                        Amérique du Sud Secours 2018 Novembre (SVT) </a>
                    <hr>
                    <a href="{{ url_for('main.region', file_name= 'SUJET - PC +SVT (Asie Pacifique) 2018.pdf') }}"> Asie
                        Pacifique 2018 (PC + SVT) </a>
                </div>
            </div>
        </div>
    </div>
</div>
    {# <a href="{{ url_for('year', id= '2017') }}">Brevet 2017 (15 sujets)</a> #}
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <script>

         $(document).ready(function() {
            $(".menu-icon").on("click", function() {
                  $("nav ul").toggleClass("showing");
            });
      });

      // Scrolling Effect

      $(window).on("scroll", function() {
            if($(window).scrollTop()) {
                  $('nav').addClass('black');
            }

            else {
                  $('nav').removeClass('black');
            }
      })
    </script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='design.css') }}">
</head>
<body>

<div class="wrapper">
         <header>

             {#    <nav>
               <div class="menu-icon">
                  <i class="fa fa-bars fa-2x"></i>
               </div>
               <div class="logo">
                  <a class = "white" href="{{ url_for('main.home') }}">EnkaSciences</a>
               </div>
               <div class="menu">
                  <ul>
                     <li><a href="{{ url_for('main.home') }}">Acceuil</a></li>
                     <li><a href="{{ url_for('main.brevet_years') }}">Annales Brevet </a></li>
                     <li><a href="{{ url_for('main.version_complete') }}">Version Complète</a></li>


                  </ul>
               </div>
            </nav>#}
 </header>
  </div>
             <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>

        <li><a href="{{ url_for('main.home') }}">Acceuil</a></li>
                     <li><a href="{{ url_for('main.brevet_years') }}">Annales Brevet </a></li>
                     <li><a href="{{ url_for('main.version_complete') }}">Version Complète</a></li>


    </ul>
  </div>
</nav>






<div class="content container">
    {% block content %}{% endblock content %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/pdf_view.html
{% extends 'layout.html'%}

{% block content %}

    <embed src= "../static/{{ file_name }}" width= "100%" height = "1290" frameborder="0">


{% endblock content %}

templates/version_complete.html
{% extends 'layout.html'%}

{% block content %}
<h1 class="margin-space align-text">Version Complète</h1>
    <hr>
    <div class="margin-space">
    <p> Si vous souhaitez avoir l'intégralité des sujets des Brevet de science 2018 et 2019, cliquez sur le lien ci-dessous pour y avoir accès par Google Drive
<br>

    </div>
        <div class="margin-space">
<a target="_blank" href="https://drive.google.com/drive/folders/1ofdPKALwEpY3dmvXdQr8H-csToxy6IN2?usp=sharing">   <button type="button" class="btn btn-primary btn-lg btn-block" ><h3> Lien vers tous les sujets (Google Drive)</h3></button></a>
        </div>

{% endblock content %}